name: Sync Fork
on:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜运行
  workflow_dispatch:     # 支持手动触发
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          owner: caleee          # 替换为原仓库所有者
          base: main             # 替换为你的 fork 分支名
          head: main             # 替换为原仓库分支名
          token: ${{ secrets.SYNC_TOKEN }}
          auto_approve: true
